version: "3"
# Media-Memo
services:
  node_server:
    build:
      context: ./node_server
    entrypoint: /app/docker/node_server/container_startup.sh
    volumes:
      - ../:/app
      - /app/docker
      - ./node_server/container_startup.sh:/app/docker/node_server/container_startup.sh
    links:
      - "mongodb"
    ports:
      - "8081:8081"
      - "25585:25585"
    stdin_open: true
    tty: true

  mongodb:
    build:
      context: ./mongodb
    entrypoint: /app/docker/mongodb/container_startup.sh
    volumes:
      - ../:/app
      - /app/docker
      - ./mongodb/container_startup.sh:/app/docker/mongodb/container_startup.sh
      - /Users/kyleblue/.mongodb/:/data/db/
      - /Users/kyleblue/.mongodb/log/:/var/log/
    ports:
      - "27017"
    stdin_open: true
    tty: true
