apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: base-traefik.bitmemo.io
      http:
        paths:
          - backend:
              serviceName: traefik-ingress-service
              servicePort: 8080
  tls:
    - secretName: certificate-secret
      hosts:
        - traefik-ui.bitmemo.io
