apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cert-ingress
  namespace: app
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths: # No host specified. Matches all incoming requests
          - path: /.well-known/acme-challenge/
            backend:
              serviceName: certificate-renewal
              servicePort: 80
  # tls: <-- Not required, this is to aquire the certificate
